function createfigure(M1, YMatrix1)
%CREATEFIGURE(M1, YMATRIX1)
%  M1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 29-Jan-2017 17:42:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0 1 2 3 4 5 6 7 8 9 10],...
    'XTick',[0 1 2 3 4 5 6 7 8 9 10]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 10]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 10]);
box(axes1,'on');
hold(axes1,'all');

% Create xlabel
xlabel('Generations');

% Create ylabel
ylabel('TaPantaOlaSorted');

% Create multiple lines using matrix input to plot
plot1 = plot(M1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,1)');
set(plot1(2),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,2)');
set(plot1(3),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,3)');
set(plot1(4),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,4)');
set(plot1(5),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,5)');
set(plot1(6),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,6)');
set(plot1(7),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,7)');
set(plot1(8),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,8)');
set(plot1(9),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,9)');
set(plot1(10),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,10)');
set(plot1(11),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,11)');
set(plot1(12),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,12)');
set(plot1(13),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,13)');
set(plot1(14),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,14)');
set(plot1(15),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,15)');
set(plot1(16),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,16)');
set(plot1(17),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,17)');
set(plot1(18),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,18)');
set(plot1(19),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,19)');
set(plot1(20),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,20)');
set(plot1(21),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,21)');
set(plot1(22),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,22)');
set(plot1(23),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,23)');
set(plot1(24),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,24)');
set(plot1(25),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,25)');
set(plot1(26),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,26)');
set(plot1(27),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,27)');
set(plot1(28),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,28)');
set(plot1(29),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,29)');
set(plot1(30),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,30)');
set(plot1(31),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,31)');
set(plot1(32),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,32)');
set(plot1(33),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,33)');
set(plot1(34),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,34)');
set(plot1(35),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,35)');
set(plot1(36),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,36)');
set(plot1(37),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,37)');
set(plot1(38),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,38)');
set(plot1(39),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,39)');
set(plot1(40),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,40)');
set(plot1(41),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,41)');
set(plot1(42),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,42)');
set(plot1(43),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,43)');
set(plot1(44),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,44)');
set(plot1(45),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,45)');
set(plot1(46),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,46)');
set(plot1(47),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,47)');
set(plot1(48),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,48)');
set(plot1(49),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,49)');
set(plot1(50),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,50)');
set(plot1(51),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,51)');
set(plot1(52),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,52)');
set(plot1(53),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,53)');
set(plot1(54),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,54)');
set(plot1(55),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,55)');
set(plot1(56),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,56)');
set(plot1(57),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,57)');
set(plot1(58),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,58)');
set(plot1(59),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,59)');
set(plot1(60),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,60)');
set(plot1(61),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,61)');
set(plot1(62),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,62)');
set(plot1(63),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,63)');
set(plot1(64),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,64)');
set(plot1(65),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,65)');
set(plot1(66),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,66)');
set(plot1(67),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,67)');
set(plot1(68),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,68)');
set(plot1(69),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,69)');
set(plot1(70),'DisplayName','TaPantaOlaSorted(:,11) vs M(:,70)');

